name: Create Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'The version for this release. eg: v1.5.2'
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Prepare Asset Package
        run: |
          rm -r .git/
          rm -r docs 
          find . -name "*.blend" -type f -delete
          find . -name "*.blend.import" -type f -delete
          mkdir -p addons/2025_04_15_gdp_kid_toy_ovni_code
          mv {.,}* addons/2025_04_15_gdp_kid_toy_ovni_code 2>/dev/null || true
          cd ..
          zip -r 2025_04_15_gdp_kid_toy_ovni_code.zip addons/
    
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ../2025_04_15_gdp_kid_toy_ovni_code.zip
          generate_release_notes: true
          tag_name: ${{ inputs.tag }}
