name: Create Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'The version for this release. eg: v1.5.2'
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Prepare Asset Package
        run: |
          [ -d .git ] && rm -r .git/
          [ -d docs ] && rm -r docs
          find . -name "*.blend" -type f -delete
          find . -name "*.blend.import" -type f -delete
          cd ..
          mkdir -p addons
          mv ${{ github.event.repository.name }} addons/${{ github.event.repository.name }}
          zip -r ${{ github.event.repository.name }}.zip addons/
    
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ../${{ github.event.repository.name }}.zip
          generate_release_notes: true
          tag_name: ${{ inputs.tag }}
